name: save_card
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.2
#  flutter_riverpod: ^2.4.1
  flutter_lints: ^2.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  build_runner: ^2.4.4
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^9.0.0
  ml_card_scanner: ^0.0.5


flutter:

  uses-material-design: true
